language: node_js
node_js:
  - "8"
os: linux

cache:
  directories:
    - node_modules

script:
  - echo TRAVIS_OS_NAME="$TRAVIS_OS_NAME"
  - python3 --version
  - node --version
  - npm --version
  - npm test

stages:
  - test
  - pack
  # - name: deploy
  #   if: branch =~ ^(master|v\d+\.\d+)

jobs:
  include:
    - stage: pack
      script:
        - echo "Packing ..."
        
    # - stage: deploy
    #   script: 
    #     - echo "Trigger Docker Hub Rebuild..."
    #     - curl -s -X POST -d '{"from":"travis"}' "$DOCKER_REBUILD_URL"

notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never
    on_cancel: never
    on_error: never
